### ISSUE TITLE
Master crashes when loading

### ISSUE THREAD

**Issue by boboben1** [oli414/AdvancedTrack#10]
Current build in master branch is crashing when I try to load a scenario.

**Comment by oli414** [comment]
Yep! The version required for what's currently on master is not yet available on the OpenRCT2.org website. Hence why I did not make the release yet.

The crash is due to a bug in OpenRCT2 where the game crashes when a plugin tries to register to an unsupported event. I can add a safe guard for this though. That said though, the plugin will not work on a version where the safe guard is triggered.

**Comment by oli414** [comment]
Fixed it in the latest commit
